FROM public.ecr.aws/lambda/python:3.10

# Install system dependencies if needed
RUN yum -y update && yum -y install gcc make

# Copy requirements and install
COPY requirements.txt  .
RUN python3.10 -m pip install -r requirements.txt -t "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY app ${LAMBDA_TASK_ROOT}/app

# Set the CMD to your handler (file.handler)
CMD ["lambda_function.lambda_handler"]
